### ISSUE TITLE
certificate has expired issue

### ISSUE THREAD

**Issue by AndrewPRK** [messagebird/messagebird-nodejs#110]
Hi.
We started get errors like 
`
{ Error: request failed: certificate has expired
    at ClientRequest.<anonymous> (/....../node_modules/messagebird/lib/messagebird.js:107:19)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 1, kind: 'Unknown' }
    `
When we use **messagebird.conversations.send** function of library. It worked before corectly.

**Comment by vallerion** [comment]
Hi @AndrewPRK,

It looks weird due to certificates will be valid until Sunday, 10 July 2022, 02:59:59 EEST. We scheduled certificates change on tomorrow you can subscribe for updates [here](https://status.messagebird.com/incidents/lpl1syk9t0v1).

**Comment by RamiBAE** [comment]
@vallerion We cannot wait till tomorrow, we are completely blocked it's broken since more than 12h
who will afford this impact on the business! and yet, we will need to wait till tomorrow!

**Comment by vallerion** [comment]
Hello @RamiBAE @AndrewPRK ! We had an incident with SSL certificates which cause issue for SDK users. https://status.messagebird.com/incidents/cbf1zx7yj9wj
So for now everything should work fine.
