### ISSUE TITLE
Incorrect access_key

### ISSUE THREAD

**Issue by zack1991** [messagebird/messagebird-nodejs#124]
```
const API_KEY = '<Access key created with owner role>';
const messagebird = require('messagebird').initClient(API_KEY);
var params = {
    'originator': 'Test',
    'recipients': [
        '+918875342870'
    ],
    'body': 'Hello, world!'
};

messagebird.messages.create(params, function (err, response) {
    if (err) {
        return console.log(err);
    }
    console.log(response);
});
```
```
Error: api error(s): Request not allowed (incorrect access_key) (code: 2, parameter: access_key)
    at IncomingMessage.<anonymous> (D:\work\node-slots-service-v2\node_modules\messagebird\lib\messagebird.js:189:23)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  statusCode: 401,
  errors: [
    {
      code: 2,
      description: 'Request not allowed (incorrect access_key)',
      parameter: 'access_key'
    }
  ]
}

```

**Comment by wcb-pont** [comment]
@zack1991 are you using access keys created from app.messagebird.com? not api keys from dashboard.messagebird.com? I am currently running into this same issue

**Comment by LuckyArdhika** [comment]
> @zack1991 are you using access keys created from app.messagebird.com? not api keys from dashboard.messagebird.com? I am currently running into this same issue

this package refer to MCP not MEP. but app.messagebird.com is MCP, so you shouln't use this package

**Comment by nirmit1509** [comment]
I'm too facing the same issue. Is there any solution or workaround for this ?

**Comment by aodinok** [comment]
Make sure you are using correct access key from dashboard.messagebird.com and not from app.bird.com as stated above. The keys are not interchangeable and work only in correct APIs.
This lib is only for old APIs that are available at dashboard.messagebird.com.

**Comment by nirmit1509** [comment]
@aodinok But on trying to sign up on dashboard.messagebird.com, it redirects to api.bird.com

**Comment by aodinok** [comment]
I am afraid that the old platforms is closed for new signups. So this library is only usable for people who have accounts already. 

Bird doesn't have yet SDK for new platform published.

**Comment by softmarshmallow** [comment]
> I am afraid that the old platforms is closed for new signups. So this library is only usable for people who have accounts already.
> 
> Bird doesn't have yet SDK for new platform published.

What a bummer for such big company

**Comment by A13k2** [comment]
> > I am afraid that the old platforms is closed for new signups. So this library is only usable for people who have accounts already.
> > Bird doesn't have yet SDK for new platform published.
> 
> What a bummer for such big company

It's ridiculous. Currently trying to implement sending an sms.
The flow on the website is just bad and not self explanatory. They still reference this package, but it's not support, the docs are not clearly separated.

**Comment by mohamed271220** [comment]
Any update on this issue or the Bird SDK
