### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by heroddube** [messagebird/messagebird-nodejs#99]
Hi, my application is getting the following console errors while using messagebird chat widget. 
What causes this error

firebase-storage-chunk-c9b44458.js:1 Uncaught (in promise) FirebaseError: Invalid collection reference. Collection references must have an odd number of segments, but channels/b298e85b-d26f-4b8e-b4dd-d15da8ea65de/agents/7a6047b8baa62bf87a6c4d2d7539c3c82d967aa51f7ad3ec272bfec8b1ab79fb has 4.
    at Ql (firebase-storage-chunk-c9b44458.js:1:220233)
    at rd (firebase-storage-chunk-c9b44458.js:1:226020)
    at Object.<anonymous> (modern-e2bc219c.js:1:136402)
    at Generator.next (<anonymous>)
    at $ (modern-e2bc219c.js:1:2534)
    at a (modern-e2bc219c.js:1:2726)

**Comment by marcelcorso** [comment]
hey @heroddube! This library is not related to the chat widget. 
You should reach out to support [here](https://support.messagebird.com/). They are better prepared to help you 🙏
